version: '3'

services:
  ml:
    image: local/ml
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/opt/project/data
      - ./output:/opt/project/output
      - ./logs:/opt/project/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - DISPLAY=192.168.100.21:0.0
    tty: true
